// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class VacancesaddTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void vacancesadd() {
    driver.Navigate().GoToUrl("http://localhost:50000/addadv");
    driver.Manage().Window.Size = new System.Drawing.Size(837, 680);
    driver.FindElement(By.Id("name")).Click();
    driver.FindElement(By.Id("name")).SendKeys("Оператор ПЭВМ");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("+375295336699");
    driver.FindElement(By.Id("price-usd")).Click();
    driver.FindElement(By.Id("price-usd")).SendKeys("300");
    driver.FindElement(By.Id("price-byn")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.LinkText("Объявления")).Click();
    driver.Close();
  }
}
